# This file uses the schema from
# https://pkg.go.dev/github.com/maruel/sillybot#Config

bot:
  llm:
    # Specify a "host:port" of an already running llama.cpp, llamafile or
    # py/llm.py server.
    #
    # Useful when you can't run both the LLM and the image generation models on
    # a single machine.
    #
    # See https://github.com/maruel/sillybot/blob/main/py/README.md for how
    # to run.
    remote: ""
    # Meta-Llama-3.1-8B-Instruct-Q5_K_M and Mistral-7B-Instruct-v0.3.Q5_K_M are
    # fast enough on unaccelerated CPU and takes 9GiB of RAM which should work
    # on most computers. Mistral has a permissive license, Llama doesn't.
    # Use "python" to use the embedded pytorch generator.
    model: hf:lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q5_K_M
  image_gen:
    # Specify a "host:port" of an already running py/image_gen.py server.
    #
    # Useful when you can't run both the LLM and the image generation models on
    # a single machine.
    #
    # See https://github.com/maruel/sillybot/blob/main/py/README.md for how
    # to run.
    remote: ""
    # Use "python" to use the embedded pytorch generator. The default SSD-1B
    # with LCM-LoRA takes about 4.6GiB of VRAM.
    model: ""
  settings:
    # TODO: fine-tune them all.
    # Default system prompt to use. You can tell it to be funny or sarcastic.
    # Beware that if you do so, tool calling won't work as well.
    prompt_system: "You are an AI assistant. You reply with short answers."
    prompt_image: "You are autoregressive language model that specializes in creating perfect, outstanding prompts for generative art models like Stable Diffusion.
      Your job is to take user ideas, capture ALL main parts, and turn into amazing dense prompts.
      You have to capture everything from the user's prompt and then use your talent to make it amazing.
      The level of the prompt you provide will directly affect the level of detail and quality of the artwork.
      So how can you refine your prompts? That is to add some keywords to the prompt, such as subject, medium, style and much more.\n
      - Subject. The subject is what you want to present in the image. A common mistake is often not depicting the subject in sufficient detail. Stable Diffusion cannot read our minds. We have to say exactly what we want. Using the names of famous people is a common technique. They will largely change the entire presentation of the image. The subject is often a place, location, a task, an object.\n
      - Medium or style. The medium is the material used to produce the artwork. Examples include illustrations, paintings, 3D renderings, Japanese anime and photography. Mediums have a strong influence because just one keyword can dramatically change the style.\n
      - Artist. Artist names are powerful modifiers. They allow you to specify the exact style using a specific artist as a reference. It's also common to use multiple artists' names to mix their styles. For example, you can add Van Gogh so that the resulting image will carry the appropriate style.\n
      - Additional details. Additional details are sweeteners added to modify the image. We can add adjectives such as sci-fi and stunningly beautiful to add a sense of ambiance to the image and make it rendered with more detail and vividness. In addition, we can add some keywords to control the color tone of the image, lighting effects, etc.\n
      I provide below examples of excellent keywords you can chose from, be creative and invent your own.\n
      character, person, ork, dog, cat, bunny, stardew valley, child, soccer
      ball, tree house, tall house, city, desert, beach, canteen, Death Star, Luke
      Skywalker, city-downtown with short buildings, sunset, cup, fox, bracelet,
      weapon, jungle, kitchen, dishwasher, Mad Max (movie), Dinosaur jurassic park,
      underwater world, plants, flowers, shells, creatures, plane, french revolution,
      ship, living room, pikachu, spagetti, painting, city street, bonsai, face,
      galaxy, fluids simulation, van, gear, landscape, supercar, driveway, villa,
      house, darth vader, minion, holidays, Paris, eye, eyes, Earth, mud, stone, goku,
      avatar, group chat, GUI, graph, data table, web page, computer, Moon, robot,
      office, laboratory, technical drawing, small world, lake, rainbow, jar
      hoodie, gold chains, dripping black goo, thug life, black and red and
      yellow paint, character composition in vector with white background, stained
      antique yellow copper paint, Dramatic Artwork, wearing leather jacket, is a DJ,
      in a nightclub, mixing live on stage, giant mixing table, Chicano airbrush art,
      Swagger! snake Culture, transparent, luxury, with ice fruits, with mint,
      connected with white, yellow and pink cream, backpack on his back, riding a
      motorcycle, magazine cover, photo for magazine, majestic, royal, tall , clear
      blue sky, Parisian, London, luxurious interior, on a clam sea, flying over
      planet, fighting, light walls, penthouse bedroom, dark walls, wooden panels,
      cute, freckles, made of buckskin, small, sitting in a movie theater, eating
      popcorn, watching a movie, gorgeous, ornate, polymer clay, Japanese, modern,
      perfect, at dawn, at dusk, sunny background, warm background, vibrant
      background, black, adventure, apocalyptic, dystopian, roof rack, abandoned,
      neighborhood, beautiful, burger, fries, setting on the horizon, shelves with
      detailed items in background, brown hair, blond hair, dark hair, turtleneck
      sweater, fireplace, stone, window, ceiling, dimly lit, living room, minimalist
      furniture, vaulted ceiling, huge room, floor to ceiling window with an ocean
      view, nighttime, closed, glass, honda cbr 650r, leather suit, glasses, seaweed
      anime, cartoon, cytus and deemo, realistic, anthopomorphic, arknights,
      very buff, painting illustration collage style, fine details, 4k resolution, 2D
      Vector Illustration, Art for Sublimation, Design Art, Chrome Art, Painting and
      Stunning Artwork, Highly Detailed Digital Painting, Airbrush Art, Highly
      Detailed Digital Artwork, digital airbrush art, detailed by Mark Brooks,
      futuristic, a masterpiece, fine details, highly detailed digital art,
      hyperrealism, highly detailed, insanely detailed, intricate, depth of field, 4K
      Commercial Food, YouTube Video Screenshot, isometric, soft colors, 20mm lens, 3d
      blender render, High quality 8K, photo realism, hyper realism, hyper detailed
      ultra intricate overwhelming realism, High Speed MO Photography, high detail,
      sharp focus, low poly, go pro footage, realistic painting, by Charles Gregory
      Artstation and Antonio Jacobsen and Edward Moran, (long shot), cinematic, fine
      carvings, fantasy, medieval, detailed post processing, unreal engineered, unreal
      5, digital texture painting, impressionist, Japanese cartoon style, octane
      render, daz, artstation, epic, concept art, matte, by artgerm, pixar,
      mark ryden, hayao miyazaki, industrial age, collage-style illustration, dream
      cinematic lighting, studio lighting, increase brightness, volumetric
      lighting, realistic shaded lighting, cozy indoor lighting, dynamic lighting,
      cozy indoor lighting, soft smooth lighting, diffuse lighting, dark, bleak, soft
      light, macro, depth of field, blur, light effect, hyper detail
      "
    prompt_labels: "You are autoregressive language model that specializes in creating perfect, dense, outstanding meme text. Your job is to take user ideas, capture ALL main parts, and turn into amazing snarky meme labels. You have to capture everything from the user's prompt and then use your talent to make it amazing filled with sarcasm. Respond only with the new meme text. Make it as succinct as possible. Use few words. Use exactly one comma. Exclude article words."


# You can remove this section. The one embedded in
# https://github.com/maruel/sillybot/blob/main/default_config.yml will be used
# automatically.
knownllms:
  # Gemma 2 family:
  # https://huggingface.co/collections/google/gemma-2-release-667d6600fd5220e7b967f315
  - source: hf:bartowski/gemma-2-9b-it-GGUF/HEAD/gemma-2-9b-it-
    packagingtype: gguf
    upstream: hf:google/gemma-2-9b-it
    # https://ai.google.dev/gemma/docs/formatting
    #prompt_encoding:
    #  begin_of_text: ""
    #  system_token_start: "<start_of_turn>user\n"
    #  system_token_end: "<end_of_turn>\n"
    #  user_token_start: "<start_of_turn>user\n"
    #  user_token_end: "<end_of_turn>\n"
    #  assistant_token_start: "<start_of_turn>model\n"
    #  assistant_token_end: "<end_of_turn>\n"
  - source: hf:bartowski/gemma-2-27b-it-GGUF/HEAD/gemma-2-27b-it-
    packagingtype: gguf
    upstream: hf:google/gemma-2-27b-it

  # Llama 3 / 3.1 family:
  # https://huggingface.co/collections/meta-llama/llama-31-669fc079a0c406a149a5738f
  # https://huggingface.co/collections/meta-llama/meta-llama-3-66214712577ca38149ebb2b6
  - source: hf:lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/HEAD/Meta-Llama-3.1-8B-Instruct-
    packagingtype: gguf
    upstream: hf:meta-llama/Meta-Llama-3.1-8B-Instruct
    # https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/
    #prompt_encoding:
    #  begin_of_text: "<|begin_of_text|>"
    #  system_token_start: "<|start_header_id|>system<|end_header_id|>\n"
    #  system_token_end: "<end_of_turn>\n"
    #  user_token_start: "<|start_header_id|>user<|end_header_id|>\n"
    #  user_token_end: "<|eot_id|>\n"
    #  assistant_token_start: "<|start_header_id|>assistant<|end_header_id|>\n"
    #  assistant_token_end: "<|eot_id|>\n"
    # TODO: This repo put Q5_K_L and higher into subdirectories, which is
    # unsupported.
  - source: hf:bartowski/Meta-Llama-3-70B-Instruct-GGUF/HEAD/Meta-Llama-3-70B-Instruct-
    packagingtype: gguf
    upstream: hf:meta-llama/Meta-Llama-3-70B-Instruct

  # Mistral family
  # https://huggingface.co/mistralai
  - source: hf:bartowski/Mistral-7B-Instruct-v0.3-GGUF/HEAD/Mistral-7B-Instruct-v0.3-
    packagingtype: gguf
    upstream: hf:mistralai/Mistral-7B-Instruct-v0.3
    # https://github.com/mistralai/mistral-common/blob/main/src/mistral_common/tokens/tokenizers/base.py
    # https://github.com/mistralai/mistral-common/blob/main/src/mistral_common/tokens/tokenizers/sentencepiece.py
    prompt_encoding:
      begin_of_text:                "<s>"
      system_token_start:           "[INST]\u2581"
      system_token_end:             " [/INST]"
      user_token_start:             "[INST]\u2581"
      user_token_end:               "[/INST]"
      assistant_token_start:        ""
      assistant_token_end:          "</s>"
      tools_available_token_start:  "[AVAILABLE_TOOLS]\u2581"
      tools_available_token_end:    "[/AVAILABLE_TOOLS]"
      tool_call_token_start:        "[TOOL_CALLS]\u2581"
      tool_call_token_end:          "</s>"
      tool_call_result_token_start: "[TOOL_RESULTS]\u2581"
      tool_call_result_token_end:   "[/TOOL_RESULTS]"
    # bartowski/Mixtral-8x22B-v0.1-GGUF only contain segmented files and I
    # didn't implement support yet.
  - source: hf:MaziyarPanahi/Mixtral-8x7B-Instruct-v0.1-GGUF/HEAD/Mixtral-8x7B-Instruct-v0.1.
    packagingtype: gguf
    upstream: hf:mistralai/Mixtral-8x7B-Instruct-v0.1

  # Phi-3/3.1 family
  # https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3
  - source: hf:bartowski/Phi-3.1-mini-4k-instruct-GGUF/HEAD/Phi-3.1-mini-4k-instruct-
    packagingtype: gguf
    upstream: hf:microsoft/Phi-3-mini-4k-instruct
    # https://huggingface.co/microsoft/Phi-3-mini-4k-instruct#chat-format
    #prompt_encoding:
    #  begin_of_text: ""
    #  system_token_start: "<|system|>\n"
    #  system_token_end: "<|end|>\n"
    #  user_token_start: "<|user|>\n"
    #  user_token_end: "<|end|>\n"
    #  assistant_token_start: "<|assistant|>\n"
    #  assistant_token_end: "<|end|>\n"
  - source: hf:bartowski/Phi-3.1-mini-128k-instruct-GGUF/HEAD/Phi-3.1-mini-128k-instruct-
    packagingtype: gguf
    upstream: hf:microsoft/Phi-3-mini-128k-instruct
  # Nobody uploaded Phi-3-small-* gguf files. Weird.
  - source: hf:bartowski/Phi-3-medium-4k-instruct-GGUF/HEAD/Phi-3-medium-4k-instruct-
    packagingtype: gguf
    upstream: hf:microsoft/Phi-3-medium-4k-instruct
  - source: hf:bartowski/Phi-3-medium-128k-instruct-GGUF/HEAD/Phi-3-medium-128k-instruct-
    packagingtype: gguf
    upstream: hf:microsoft/Phi-3-medium-128k-instruct

  # Qwen 2 family
  # https://huggingface.co/collections/Qwen/qwen2-6659360b33528ced941e557f
  - source: hf:Qwen/Qwen2-0.5B-Instruct-GGUF/HEAD/qwen2-0_5b-instruct-
    packagingtype: gguf
    upstream: hf:Qwen/Qwen2-0.5B-Instruct
    # https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md#special-tokens
    #prompt_encoding:
    #  begin_of_text: ""
    #  system_token_start: "<|im_start|>\n"
    #  system_token_end: "<|im_end|>\n"
    #  user_token_start: "<|im_start|>\n"
    #  user_token_end: "<|im_end|>\n"
    #  assistant_token_start: ""
    #  assistant_token_end: "<|end_of_text|>\n"
  - source: hf:Qwen/Qwen2-1.5B-Instruct-GGUF/HEAD/qwen2-1_5b-instruct-
    packagingtype: gguf
    upstream: hf:Qwen/Qwen2-1.5B-Instruct
  - source: hf:Qwen/Qwen2-7B-Instruct-GGUF/HEAD/qwen2-7b-instruct-
    packagingtype: gguf
    upstream: hf:Qwen/Qwen2-7B-Instruct
